### PR TITLE
Fix generation of functions with union params

### LINKED ISSUE #615: fail to generate cs file for function with union as argument
```cpp
#include <stdio.h>
typedef union {
  int c;
  int d[10];
} union_t;
struct test_struct2                                                            
  int b;
  union_t u;
};
int func_union(union_t u) {
}

int func(struct test_struct2 *p) {
}
```
The code above failed to generate cs file for ```func_union```.  
I think CppSharp omitted functions that get union structure as an argument.
Could someone help me to resolve this issue ? or this feature is not implemented yet ?

### PR DESCRIPTION
**Pull request by genuinelucifer**
Fixes #615

### CODE REVIEW

File: tests/Common/Common.h [hunk 1]
```diff
@@ -1072,3 +1072,10 @@ class DLL_API DerivedFromTemplateInstantiationWithVirtual : public TemplateWithV
     DerivedFromTemplateInstantiationWithVirtual();
 };
 
+typedef DLL_API union {
+	int c;
```
Comment (ddobrev) [inline tests/Common/Common.h]: Please just use 4 spaces instead of tabs here and below and I'll merge.

**Comment by genuinelucifer** [comment]
@ddobrev Done.
