### PR TITLE
Fix ambiguous conversion functions

### LINKED ISSUE #1415: Two conversion operators (T* and T&) end up generating two operators returning the same type (T*)
```.cpp
class Class
{
public:
    operator short *();
    operator short &();
};
```

OS: Windows

##### Used settings

Target: MSVC

##### Stack trace or incompilable generated code

```.cs
// DEBUG: operator short*()
public static implicit operator short*(global::TestLib.Class __op)
{
    if (ReferenceEquals(__op, null))
        throw new global::System.ArgumentNullException("__op", "Cannot be null because it is a C++ reference (&).");
    var __arg0 = __op.__Instance;
    var __ret = __Internal.OperatorConversion(__arg0);
    return __ret;
}

// DEBUG: operator short&()
public static implicit operator short*(global::TestLib.Class __op) // CS0057: Duplicated user-defined conversion in type 'Class'
{
    if (ReferenceEquals(__op, null))
        throw new global::System.ArgumentNullException("__op", "Cannot be null because it is a C++ reference (&).");
    var __arg0 = __op.__Instance;
    var __ret = __Internal.OperatorConversion_1(__arg0);
    return __ret;
}
```

### PR DESCRIPTION
**Pull request by josetr**
Fixes #1415

### CODE REVIEW

File: src/Generator/Passes/CheckAmbiguousFunctions.cs [hunk 1]
```diff
@@ -172,6 +173,22 @@ private static bool CheckConstnessForAmbiguity(Function function, Function overl
...
         }
 
+        private bool CheckConversionAmbiguity(Function function, Function overload)
+        {
+            var method1 = function as Method;
+            var method2 = overload as Method;
+            if (method1 == null || method2 == null)
+                return false;
+
+            if (method1.ReturnType.Type.ToString() == method2.ReturnType.Type.ToString())
```
Comment (ddobrev) [inline src/Generator/Passes/CheckAmbiguousFunctions.cs:183]: Please use `Type.Equals` instead.

Comment (josetr) [reply src/Generator/Passes/CheckAmbiguousFunctions.cs:183]: @ddobrev I tried that and it only works for `BuiltinType` types.

Comment (ddobrev) [reply src/Generator/Passes/CheckAmbiguousFunctions.cs:183]: If so, we have a bug. What did you try: `ReturnType.Equals` or `ReturnType.Type.Equals`?

Comment (josetr) [reply src/Generator/Passes/CheckAmbiguousFunctions.cs:183]: `ReturnType.Type` because `ReturnType` includes the `const` qualifier which I didn't care about.
