### PR TITLE
Ignored the generated code for variable-sized array of a class/struct

### LINKED ISSUE #777: Invalid generated code for variable array global variable
##### Brief Description

I would  like to generate bindings for [Gammu](https://github.com/gammu/gammu), a C library that is freely available. when trying to do so it gives an error saying it does not find the gammu.lib file nor the headers. I suspect I am not putting them at the right place. where should I put the files so that cppsharp sees them ? 

OS: Windows 
here is a sample of my generator

` class MyGenerator : ILibrary
    {

        private const string GammuRootPath = @"C:\Program Files\Gammu 1.38.1";
        private const string GammuIncludePath = GammuRootPath + @"\include\";
        private const string GammuLibPath = GammuRootPath + @"\lib\";

        public void Postprocess(Driver driver, ASTContext ctx)
        {
            //throw new NotImplementedException();
        }

        public void Preprocess(Driver driver, ASTContext ctx)
        {
            //throw new NotImplementedException();
        }

        public void Setup(Driver driver)
        {
          

            PrepareDriver(driver);

        }

        private static void PrepareDriver(Driver driver)
        {
            var drOptions = driver.Options;
            drOptions.GeneratorKind = GeneratorKind.CSharp;
            //drOptions.CompileCode = true;
            drOptions.OutputDir = "GammuSharp";
            drOptions.LibraryName = "libGammuSharp";
          
            drOptions.Libraries.Add("Gammu.lib");
            
            drOptions.OutputInteropIncludes = true;
            drOptions.GenerateInternalImports = true;
            //drOptions.Target = CompilationTarget.StaticLibrary;
            drOptions.Platform = TargetPlatform.Windows;
            drOptions.VsVersion = VisualStudioVersion.VS2012;
            drOptions.UseHeaderDirectories = true;
            
            //drOptions.OutputNamespace = "GammuSharp";
            
            // header files to include

            //drOptions.Headers.Add(GammuIncludePath + "gammu.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-wap.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-unicode.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-types.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-statemachine.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-smsd.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-settings.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-security.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-ringtone.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-nokia.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-misc.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-message.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-memory.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-limits.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-keys.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-inifile.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-info.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-file.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-error.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-debug.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-datetime.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-config.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-category.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-callback.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-call.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-calendar.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-bitmap.h");
            //drOptions.Headers.Add(GammuIncludePath + "gammu-backup.h");

        }

        public void SetupPasses(Driver driver)
        {
            
        }
    }
`

### PR DESCRIPTION
**Pull request by mohtamohit**
Fixes #777

### CODE REVIEW

File: src/Generator/Types/TypeIgnoreChecker.cs [hunk 1]
```diff
@@ -138,14 +138,48 @@ public override bool VisitArrayType(ArrayType array, TypeQualifiers quals)
                 return false;
             }
 
+            var arrayElemType = array.Type.Desugar();
+
+            if (array.SizeType == ArrayType.ArraySize.Incomplete && array.QualifiedType.Qualifiers.IsConst)
+            {
+
```
Comment (ddobrev) [inline src/Generator/Types/TypeIgnoreChecker.cs]: Remove the empty line.

File: src/Generator/Types/TypeIgnoreChecker.cs [hunk 2]
```diff
@@ -138,14 +138,48 @@ public override bool VisitArrayType(ArrayType array, TypeQualifiers quals)
...
+                if (!(arrayElemType.IsPrimitiveType(PrimitiveType.Bool) ||
```
Comment (ddobrev) [inline src/Generator/Types/TypeIgnoreChecker.cs]: You can and should use IsPrimitiveType without a parameter instead.

File: src/Generator/Types/TypeIgnoreChecker.cs [hunk 3]
```diff
@@ -138,14 +138,21 @@ public override bool VisitArrayType(ArrayType array, TypeQualifiers quals)
                 return false;
             }
 
+            var arrayElemType = array.Type.Desugar();
+
+            if (array.SizeType == ArrayType.ArraySize.Incomplete && array.QualifiedType.Qualifiers.IsConst
```
Comment (ddobrev) [inline src/Generator/Types/TypeIgnoreChecker.cs]: Move the second condition to a new line.

File: src/Generator/Types/TypeIgnoreChecker.cs [hunk 4]
```diff
@@ -138,14 +138,21 @@ public override bool VisitArrayType(ArrayType array, TypeQualifiers quals)
...
+                && arrayElemType.IsPrimitiveType())
```
Comment (ddobrev) [inline src/Generator/Types/TypeIgnoreChecker.cs]: Move && to the previous line.

File: tests/CSharp/CSharp.h [hunk 5]
```diff
@@ -1203,4 +1203,7 @@ class DLL_API TestIndexedProperties
 int TestIndexedProperties::operator[](const int& key)
 {
     return key;
-}
\ No newline at end of file
+}
+
+struct SomeStruct {};
```
Comment (ddobrev) [inline tests/CSharp/CSharp.h]: No need for a new type, just use an existing one.

File: tests/CSharp/CSharp.h [hunk 6]
```diff
@@ -1203,4 +1203,7 @@ class DLL_API TestIndexedProperties
...
+extern const SomeStruct SomeArray[];
```
Comment (ddobrev) [inline tests/CSharp/CSharp.h]: As I said, name after what you test. For example, you could christen it "ArrayOfVariableSize".
