### PR TITLE
Fixed the generated C# for const ref parameter of Indexer

### LINKED ISSUE #628: Error generating code for const ref subscript operator
Add to `Common.h` TestIndexedProperties:

``` cpp
    int operator[](const int& key);
```

Error:

```
../gen/Common/Common.cs(4932,24): error CS0213: You cannot use the fixed statement to take the address of an already fixed expression
../gen/Common/Common.cs(4932,46): error CS0266: Cannot implicitly convert type `int**' to `int*'. An explicit conversion exists (are you missing a cast?)
```

C# code:

``` csharp
        public int this[int* key]
        {
            get
            {
                fixed (int* __refParamPtr0 = &key)
                {
                    var arg0 = __refParamPtr0;
                    var __ret = Internal.OperatorSubscript_9((__Instance + __PointerAdjustment), arg0);
                    return __ret;
                }
            }
        }
```

### PR DESCRIPTION
**Pull request by mohtamohit**
Fixes #628

### CODE REVIEW

File: src/Generator/Generators/CSharp/CSharpMarshal.cs [hunk 1]
```diff
@@ -492,7 +492,7 @@ public override bool VisitPointerType(PointerType pointer, TypeQualifiers quals)
 
             var pointee = pointer.Pointee.Desugar();
             if (Context.Function != null && pointer.IsPrimitiveTypeConvertibleToRef() &&
-                Context.MarshalKind != MarshalKind.VTableReturnValue)
+                Context.MarshalKind != MarshalKind.VTableReturnValue && Context.Function.OperatorKind != CXXOperatorKind.Subscript)
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: Move the new condition to a new line - notice that this line is too long compared to the others.

File: src/Generator/Generators/CSharp/CSharpMarshal.cs [hunk 2]
```diff
@@ -507,7 +507,7 @@ public override bool VisitPointerType(PointerType pointer, TypeQualifiers quals)
                 else
                 {
                     Context.Before.WriteLine(
-                        $"fixed ({pointer} {refParamPtr} = &{Context.Parameter.Name})");
+                        $"fixed ({pointer} {refParamPtr} = &{Context.Parameter.Name})");
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: Remove the space at the end.

File: src/Generator/Generators/CSharp/CSharpMarshal.cs [hunk 3]
```diff
@@ -534,7 +534,7 @@ public override bool VisitPointerType(PointerType pointer, TypeQualifiers quals)
                 {
                     Context.Return.Write(MarshalStringToUnmanaged(Context.Parameter.Name));
                     Context.Cleanup.WriteLine("Marshal.FreeHGlobal({0});", Context.ArgName);
-                }
+                }
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: Remove the space at the end.

File: src/Generator/Generators/CSharp/CSharpMarshal.cs [hunk 4]
```diff
@@ -580,13 +580,16 @@ public override bool VisitPointerType(PointerType pointer, TypeQualifiers quals)
                 if (isRefParam)
                 {
                     var typeName = Type.TypePrinterDelegate(finalPointee);
-
-                    if (param.IsInOut)
-                        Context.Before.WriteLine("{0} _{1} = {1};", typeName, param.Name);
+                    if (Context.Function.OperatorKind != CXXOperatorKind.Subscript)
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: Positive conditions are a little faster to understand when reading code so invert the conditional.

File: src/Generator/Generators/CSharp/CSharpMarshal.cs [hunk 5]
```diff
@@ -580,13 +580,16 @@ public override bool VisitPointerType(PointerType pointer, TypeQualifiers quals)
...
+                    {
+                        if (param.IsInOut)
+                            Context.Before.WriteLine("{0} _{1} = {1};", typeName, param.Name);
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: Now that you're changing this anyway, convert to interpolated strings this line and the other 3 in the changed block.

File: src/Generator/Generators/CSharp/CSharpMarshal.cs [hunk 6]
```diff
@@ -580,13 +580,16 @@ public override bool VisitPointerType(PointerType pointer, TypeQualifiers quals)
...
+                        else
+                            Context.Before.WriteLine("{0} _{1};", typeName, param.Name);
+                        Context.Return.Write("&_{0}", param.Name);
+                    }
                     else
-                        Context.Before.WriteLine("{0} _{1};", typeName, param.Name);
-
-                    Context.Return.Write("&_{0}", param.Name);
+                        Context.Return.Write("{0}", param.Name);
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: Just write the name, no need for either formatting or interpolation.

File: tests/CSharp/CSharp.Tests.cs [hunk 7]
```diff
@@ -834,4 +834,16 @@ public void TestGenerationOfArraySetter()
...
\ No newline at end of file
+
+    [Test]
+    public void TestConstRefIndexer()
+    {
+        using (var indexproperty = new TestIndexedProperties())
+        {
+            int a = 2;
+            int* b = &a;
+            int* c = &a;
```
Comment (ddobrev) [inline tests/CSharp/CSharp.Tests.cs]: No need for a second variable with the same value.

File: tests/CSharp/CSharp.Tests.cs [hunk 8]
```diff
@@ -834,4 +834,16 @@ public void TestGenerationOfArraySetter()
...
-}
\ No newline at end of file
+
+    [Test]
+    public void TestConstRefIndexer()
+    {
+        using (var indexproperty = new TestIndexedProperties())
+        {
+            int a = 2;
+            int* b = &a;
```
Comment (ddobrev) [inline tests/CSharp/CSharp.Tests.cs]: No need for a local variable, you can just write &a in the indexer.

File: tests/CSharp/CSharp.Tests.cs [hunk 9]
```diff
@@ -834,4 +834,16 @@ public void TestGenerationOfArraySetter()
...
+            int* c = &a;
+            Assert.AreEqual(indexproperty[b], indexproperty[c]);
```
Comment (ddobrev) [inline tests/CSharp/CSharp.Tests.cs]: Since b and c have the same value, you compare two identical values which is pointless. Compare to a hard-coded value instead.
In addition, please use the Assert.That(... Is.EqualTo(...)) syntax because we have long decided to use it over the old one.

File: tests/CSharp/CSharp.h [hunk 10]
```diff
@@ -1193,3 +1193,14 @@ struct HasComplexArray
 {
     ComplexArrayElement complexArray[ARRAY_LENGTH_MACRO];
 };
+
+class DLL_API TestIndexedProperties
+{
+public:
+	int operator[](const int& key);
```
Comment (ddobrev) [inline tests/CSharp/CSharp.h]: You have used a tab here while we use 4 spaces in C++ too. You could change your VS settings in order not to fix it manually each time.

File: tests/CSharp/CSharp.h [hunk 11]
```diff
@@ -1193,3 +1193,14 @@ struct HasComplexArray
...
+};
+
+int TestIndexedProperties::operator[](const int& key)
+{
+	return key;
```
Comment (ddobrev) [inline tests/CSharp/CSharp.h]: Tab -> 4 spaces.

File: src/Generator/Generators/CSharp/CSharpMarshal.cs [hunk 12]
```diff
@@ -580,13 +581,18 @@ public override bool VisitPointerType(PointerType pointer, TypeQualifiers quals)
                 if (isRefParam)
                 {
                     var typeName = Type.TypePrinterDelegate(finalPointee);
-
-                    if (param.IsInOut)
-                        Context.Before.WriteLine("{0} _{1} = {1};", typeName, param.Name);
+                    if (Context.Function.OperatorKind == CXXOperatorKind.Subscript)
+                    {
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: We do not use braces with single statements.

File: src/Generator/Generators/CSharp/CSharpMarshal.cs [hunk 13]
```diff
@@ -580,13 +581,18 @@ public override bool VisitPointerType(PointerType pointer, TypeQualifiers quals)
...
+                        Context.Return.Write("key");
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: You have forgotten to replace your test code with the real code.

File: src/Generator/Generators/CSharp/CSharpMarshal.cs [hunk 14]
```diff
@@ -580,13 +581,18 @@ public override bool VisitPointerType(PointerType pointer, TypeQualifiers quals)
...
                     else
-                        Context.Before.WriteLine("{0} _{1};", typeName, param.Name);
-
-                    Context.Return.Write("&_{0}", param.Name);
+                    {
+                        if (param.IsInOut)
+                            Context.Before.WriteLine($"{typeName} _{param.Name} = {param.Name};");
+                        else
+                            Context.Before.WriteLine($"{typeName} _{param.Name};");
+                        Context.Return.Write($"&_{param.Name}");
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: Restore the empty line before this statement.
