### PR TITLE
Fixed missing namespace problem.

### LINKED ISSUE #590: Missed namespace
Minimal steps to reproduce is specified below.
C++ code:
```
namespace NamespaceA
{
	CS_VALUE_TYPE class DLL_API A
	{
	};
}
namespace NamespaceB
{
	class DLL_API B
	{
	public:
		void Function(CS_OUT NamespaceA::A &a);
	};
}
```
Fragment of generated C# code:
```
        public void Function(out NamespaceA.A a)
        {
            a = new NamespaceA.A();
            var __arg0 = new A.Internal();
            var arg0 = new global::System.IntPtr(&__arg0);
            Internal.Function_0((__Instance + __PointerAdjustment), arg0);
            NamespaceA.A __result0;
            if (arg0 == IntPtr.Zero) __result0 = new NamespaceA.A();
            else __result0 = NamespaceA.A.__CreateInstance(arg0);
            a = __result0;
        }
```
Second function line should be:
var __arg0 = new **NamespaceA.**A.Internal();
Generated code is not compilable due to missed namespace.
This problem can be reproduced only if **A** is struct in C#.

### PR DESCRIPTION
**Pull request by genuinelucifer**
closes #590

### CODE REVIEW

File: src/Generator/Generators/CSharp/CSharpMarshal.cs [hunk 1]
```diff
@@ -501,8 +501,10 @@ public override bool VisitPointerType(PointerType pointer, TypeQualifiers quals)
             {
                 if (Context.Parameter.Usage == ParameterUsage.Out)
                 {
+                    var TypePrinter = new CSharpTypePrinter(Context.Driver);
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: The marshaller already has a type printer contained in a field so please use that instead of creating a new one.

Comment (genuinelucifer) [inline src/Generator/Generators/CSharp/CSharpMarshal.cs]: @ddobrev Done.

**Comment by tritao** [comment]
Thanks a lot @genuinelucifer!
