### PR TITLE
Fixed the C# generation for functions with typedefed function pointers as params

### LINKED ISSUE #898: Invalid code generated from typedef function pointers
##### Brief Description
Hello,
I am trying to wrap an API written in C. In the API there are functions that take a typedef function pointer as an argument, like so:

`PJ_DEF(pj_status_t) pjsip_register_uri_parser( char *scheme,
					       pjsip_parse_uri_func *func)`

with the following typedef:

`typedef void* (pjsip_parse_uri_func)(pj_scanner *scanner, pj_pool_t *pool,
				     pj_bool_t parse_params);`

From this CppSharp generates the following incompilable C#-Code:

`public static int PjsipRegisterUriParser(sbyte* scheme, Func<global::System.IntPtr, global::pjsua.PjScanner scanner, global::pjsua.PjPoolT pool, int parse_params> func) {...}`

The way I see it the typeparameters in the C#-Delegate should not have the identifiers left over. Is this a bug or am I simply using CppSharp wrongly?

OS: Windows, using the CppSharp NuGet package version 0.8.13 with Visual Studio 2017
Target: MSVC

### PR DESCRIPTION
**Pull request by mohtamohit**
Fixes #898

### CODE REVIEW

File: tests/CSharp/CSharp.h [hunk 1]
```diff
@@ -1217,3 +1217,14 @@ void* TestIndexedProperties::operator[](size_t n) const
 extern const ComplexArrayElement ArrayOfVariableSize[];
 
 void useStdStringJustAsParameter(std::string s);
+
+typedef void* (typedefedFuncPtr)(Foo *a, Bar b);
+
+class DLL_API HasFuncWithTypedefedFuncPtrAsParam
```
Comment (ddobrev) [inline tests/CSharp/CSharp.h]: We try to keep tests as short as possible so we don't use classes unless we test them. For this bug a free function is enough.

File: tests/CSharp/CSharp.h [hunk 2]
```diff
@@ -1217,3 +1217,14 @@ void* TestIndexedProperties::operator[](size_t n) const
 extern const ComplexArrayElement ArrayOfVariableSize[];
 
 void useStdStringJustAsParameter(std::string s);
+
+typedef void* (typedefedFuncPtr)(Foo *a, Bar b);
```
Comment (ddobrev) [inline tests/CSharp/CSharp.h]: Unless these parameter cause the bug, remove them.

File: src/Generator/Generators/CSharp/CSharpTypePrinter.cs [hunk 3]
```diff
@@ -661,6 +661,10 @@ public override TypePrinterResult VisitParameter(Parameter param, bool hasName)
             var extension = param.Kind == ParameterKind.Extension ? "this " : string.Empty;
             var usage = GetParameterUsage(param.Usage);
 
+            if (!hasName &&
+                (param.DefaultArgument == null || !Options.GenerateDefaultValuesForArguments))
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpTypePrinter.cs]: It's impossible to have a default value without a name anyway, so only leave the check for a name.

File: src/Generator/Generators/CSharp/CSharpTypePrinter.cs [hunk 4]
```diff
@@ -655,6 +655,9 @@ public override TypePrinterResult VisitParameter(Parameter param, bool hasName)
             typeBuilder.Append(printedType.NameSuffix);
             var type = typeBuilder.ToString();
 
+            if (param.QualifiedType.Type.GetFinalQualifiedPointee().Type.Desugar() is FunctionType)
```
Comment (ddobrev) [inline src/Generator/Generators/CSharp/CSharpTypePrinter.cs]: For simplicity just check if the dictionary contains the param. If it does, there's no way it got there in the first place unless it has a function type.

File: src/Generator/Passes/DelegatesPass.cs [hunk 5]
```diff
@@ -53,17 +53,33 @@ public override bool VisitASTContext(ASTContext context)
...
+        private void AddDelegatesToDictionary(Declaration decl, Module module)
         {
-            if (!base.VisitMethodDecl(method) || !method.IsVirtual || method.Ignore)
-                return false;
-
-            var @params = method.GatherInternalParams(Context.ParserOptions.IsItaniumLikeAbi, true).ToList();
-            var delegateName = GenerateDelegateSignature(@params, method.ReturnType);
-
-            var module = method.TranslationUnit.Module;
+            var callingConvention = new CallingConvention();
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Do not initialise these local variables, they are assigned in either case.

File: src/Generator/Passes/DelegatesPass.cs [hunk 6]
```diff
@@ -89,39 +105,68 @@ public override bool VisitMethodDecl(Method method)
             }
 
             var @delegate = new TypedefDecl
-                {
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Restore the indentation as it was.

File: src/Generator/Passes/DelegatesPass.cs [hunk 7]
```diff
@@ -89,39 +105,68 @@ public override bool VisitMethodDecl(Method method)
...
+                    var module = method.TranslationUnit.Module;
+                    AddDelegatesToDictionary(param, module);
+                }
+            }
+            return;
+        }
+        
+        public override bool VisitMethodDecl(Method method)
+        {
+            // Hack : We should shift this call to VisitFunctionTypeParameters in VisitParameter. We can't do it now
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Spell HACK like this, all upper.

File: src/Generator/Passes/DelegatesPass.cs [hunk 8]
```diff
@@ -89,39 +105,68 @@ public override bool VisitMethodDecl(Method method)
...
+            // because we need to use the module and a since a parameter's namespace is null, we can't reach the
+            // translation unit and thus the module
+            if (!method.Ignore)
+                VisitFunctionTypeParameters(method);
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Move the call after the check below.

File: tests/CSharp/CSharp.Tests.cs [hunk 9]
```diff
@@ -854,4 +854,14 @@ public void TestVoidPtrReturningIndexer()
             Assert.That(*((int*) indexproperty[n]), Is.EqualTo(21));
         }
     }
+
+    [Test]
+    public void TestFuncWithTypedefedFuncPtrAsParam()
+    {
+        using (var hasFuncWithTypedefedFuncPtrAsParam = new HasFuncWithTypedefedFuncPtrAsParam())
+        {
+            CSharp.Delegates.Func_int_IntPtr_CSharp_Bar___Internal function = (System.IntPtr a, CSharp.Bar.__Internal b) => 5;
```
Comment (ddobrev) [inline tests/CSharp/CSharp.Tests.cs]: Replace the fully qualified name with a using. Remove the parameter types of the lambda.

File: src/Generator/Passes/DelegatesPass.cs [hunk 10]
```diff
@@ -89,39 +105,68 @@ public override bool VisitMethodDecl(Method method)
...
             libsDelegates[module].Add(delegateString, existingDelegate);
 
             namespaceDelegates.Declarations.Add(@delegate);
+        }
+
+        private void VisitFunctionTypeParameters(Method method)
+        {
+            foreach(var param in method.Parameters)
+            {
+                if (param.QualifiedType.Type.GetFinalQualifiedPointee().Type.Desugar() is FunctionType)
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: This check is both too long and incomplete. First you need to ensure you actually have a pointee by checking the type is an address:

    var paramType = param.Type.Desugar();
    paramType.IsAddress()

Then shorten the rest to:

    paramType.GetFinalPointee().Desugar() is FunctionType

Also, in this particular case change the condition to LINQ, use its SQL syntax.

File: src/Generator/Passes/DelegatesPass.cs [hunk 11]
```diff
@@ -53,17 +53,33 @@ public override bool VisitASTContext(ASTContext context)
...
-            var delegateName = GenerateDelegateSignature(@params, method.ReturnType);
-
-            var module = method.TranslationUnit.Module;
+            CallingConvention callingConvention;
+            bool isDependent = false;
+            QualifiedType returnType;
+            List<Parameter> @params;
+            if (decl is Method)
+            {
+                var method = decl as Method;
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Cast directly.

File: src/Generator/Passes/DelegatesPass.cs [hunk 12]
```diff
@@ -53,17 +53,33 @@ public override bool VisitASTContext(ASTContext context)
...
+                @params = method.GatherInternalParams(Context.ParserOptions.IsItaniumLikeAbi, true).ToList();
+                callingConvention = method.CallingConvention;
+                isDependent = method.IsDependent;
+                returnType = method.ReturnType;
+            }
+            else
+            {
+                var param = decl as Parameter;
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Cast directly.

File: src/Generator/Passes/DelegatesPass.cs [hunk 13]
```diff
@@ -53,17 +53,33 @@ public override bool VisitASTContext(ASTContext context)
...
+                var funcTypeParam = param.QualifiedType.Type.GetFinalQualifiedPointee().Type.Desugar() as FunctionType;
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Shorten to:

    param.Type.Desugar().GetFinalPointee().Desugar()

File: src/Generator/Passes/DelegatesPass.cs [hunk 14]
```diff
@@ -96,36 +112,63 @@ public override bool VisitMethodDecl(Method method)
...
+                                    CallingConvention = callingConvention,
+                                    IsDependent = isDependent,
                                     Parameters = @params,
-                                    ReturnType = method.ReturnType
+                                    ReturnType = returnType
                                 }))),
                     Namespace = namespaceDelegates,
                     IsSynthetized = true,
-                    Access = AccessSpecifier.Private
+                    Access = (decl is Method) ? AccessSpecifier.Private : AccessSpecifier.Public
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Remove ().

File: src/Generator/Passes/DelegatesPass.cs [hunk 15]
```diff
@@ -96,36 +112,63 @@ public override bool VisitMethodDecl(Method method)
...
 
             libsDelegates[module].Add(delegateString, existingDelegate);
 
             namespaceDelegates.Declarations.Add(@delegate);
+        }
 
-            return true;
+        private void VisitFunctionTypeParameters(Method method)
+        {
+            foreach (var param in method.Parameters.Where(
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Let me just tell you how I want it written:

foreach (var param in from param in method.Parameters
                                     let paramType = param.Type.Desugar()
                                     where paramType.IsAddress() &&
                                         paramType.GetFinalPointee().Type.Desugar() is FunctionType)

File: src/Generator/Passes/DelegatesPass.cs [hunk 16]
```diff
@@ -96,36 +112,66 @@ public override bool VisitMethodDecl(Method method)
...
             namespaceDelegates.Declarations.Add(@delegate);
+        }
 
-            return true;
+        private void VisitFunctionTypeParameters(Method method)
+        {
+            foreach (var param in from param in method.Parameters
+                                  let paramType = param.Type.Desugar()
+                                  where paramType.IsAddress() &&
+                                  paramType.GetFinalQualifiedPointee().Type.Desugar() is FunctionType
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Indent with 4 spaces and use paramType.GetFinalPointee().Desugar() instead, as I said earlier.

File: tests/CSharp/CSharp.h [hunk 17]
```diff
@@ -1217,3 +1217,13 @@ void* TestIndexedProperties::operator[](size_t n) const
 extern const ComplexArrayElement ArrayOfVariableSize[];
 
 void useStdStringJustAsParameter(std::string s);
+
+typedef int (typedefedFuncPtr)(Foo *a, Bar b);
+
+class DLL_API HasFuncWithTypedefedFuncPtrAsParam
```
Comment (ddobrev) [inline tests/CSharp/CSharp.h]: As I said in the very beginning, we don't need an entire class for this. Use a single function.

File: src/Generator/Passes/DelegatesPass.cs [hunk 18]
```diff
@@ -96,36 +112,74 @@ public override bool VisitMethodDecl(Method method)
...
+            // because we need to use the module and a since a parameter's namespace is null, we can't reach the
+            // translation unit and thus the module
+            VisitFunctionTypeParameters(function);
 
             return true;
         }
 
+        public override bool VisitMethodDecl(Method method)
+        {
+            if (!base.VisitMethodDecl(method) || method.Ignore)
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Now that you do the work in VisitFunction, restore the conditional as it was.

File: src/Generator/Passes/DelegatesPass.cs [hunk 19]
```diff
@@ -96,36 +112,74 @@ public override bool VisitMethodDecl(Method method)
...
 
             namespaceDelegates.Declarations.Add(@delegate);
+        }
+
+        private void VisitFunctionTypeParameters(Function function)
+        {
+            foreach (var param in from param in function.Parameters
+                                  let paramType = param.Type.Desugar()
+                                  where paramType.IsAddress() &&
+                                  paramType.GetFinalPointee().Desugar() is FunctionType
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Indent 4 spaces.

File: tests/CSharp/CSharp.cpp [hunk 20]
```diff
@@ -1354,3 +1354,10 @@ DLL_API int useDuplicateDeclaredStruct(DuplicateDeclaredStruct* s)
 void useStdStringJustAsParameter(std::string s)
 {
 }
+
+int funcWithTypedefedFuncPtrAsParam(typedefedFuncPtr *func)
+{
+    Foo* a;
```
Comment (ddobrev) [inline tests/CSharp/CSharp.cpp]: Initialise to 0.

File: tests/CSharp/CSharp.Tests.cs [hunk 21]
```diff
@@ -854,4 +855,11 @@ public void TestVoidPtrReturningIndexer()
             Assert.That(*((int*) indexproperty[n]), Is.EqualTo(21));
         }
     }
+
+    [Test]
```
Comment (ddobrev) [inline tests/CSharp/CSharp.Tests.cs]: Ignore the test on Windows because AppVeyor causes trouble.

File: src/Generator/Passes/DelegatesPass.cs [hunk 22]
```diff
@@ -96,36 +112,71 @@ public override bool VisitMethodDecl(Method method)
...
 
             libsDelegates[module].Add(delegateString, existingDelegate);
 
             namespaceDelegates.Declarations.Add(@delegate);
+        }
+
+        private void VisitFunctionTypeParameters(Function function)
+        {
+            foreach (var param in from param in function.Parameters
+                         let paramType = param.Type.Desugar()
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: I didn't mean to indent all of it, just the line the remark was at.

File: src/Generator/Passes/DelegatesPass.cs [hunk 23]
```diff
@@ -96,36 +112,71 @@ public override bool VisitMethodDecl(Method method)
...
+            // because we need to use the module and a since a parameter's namespace is null, we can't reach the
+            // translation unit and thus the module
+            VisitFunctionTypeParameters(function);
 
             return true;
         }
 
+        public override bool VisitMethodDecl(Method method)
+        {
+            if (!base.VisitMethodDecl(method) || method.Ignore || !method.IsVirtual)
```
Comment (ddobrev) [inline src/Generator/Passes/DelegatesPass.cs]: Swap Ignore and IsVirtual so that there are less changes.

File: tests/CSharp/CSharp.Tests.cs [hunk 24]
```diff
@@ -854,4 +855,11 @@ public void TestVoidPtrReturningIndexer()
             Assert.That(*((int*) indexproperty[n]), Is.EqualTo(21));
         }
     }
+
+    [Test, Platform(Exclude = "Windows", Reason = "AppVeyor causing trouble.")]
```
Comment (ddobrev) [inline tests/CSharp/CSharp.Tests.cs]: Copy the reason from the other test excluded on Windows.
