### PR TITLE
Fix anonymous member name colliding with enclosing type name

### LINKED ISSUE #1414: Inheriting from a base class that uses unions and lives in another file generates uncompilable code
I've added a comment in the generated code which shows the exact line where the error `CS0542` happens. This only happens if the base class lives in another file. If both classes live in the same file then a completely different code is generated which doesn't have this issue.

file1.h
```.cs
struct StructBase {
    union {
        float arr[2];
        struct {
            float a, b;
        };
    };
};
```

file2.h
```
#include "file.h"
struct Struct : public StructBase { };
```

OS: Windows

##### Used settings

Target: MSVC

##### Stack trace or incompilable generated code

```.cs
// DEBUG: struct StructBase
// DEBUG: {
// DEBUG:     union
// DEBUG:     {
// DEBUG:         float arr[2];
// DEBUG:         struct
// DEBUG:         {
// DEBUG:             float a, b;
// DEBUG:         };
// DEBUG:     };
// DEBUG: }
public unsafe partial class StructBase : IDisposable
{
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public partial struct __Internal
    {
        [FieldOffset(0)]
        internal fixed float arr[2];

        [FieldOffset(0)]
        internal global::TestLib.StructBase._0._0.__Internal _0;

        [SuppressUnmanagedCodeSecurity]
        [DllImport("TestLib", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="??0StructBase@@QEAA@AEBU0@@Z")]
        internal static extern global::System.IntPtr cctor(global::System.IntPtr __instance, global::System.IntPtr _0);
    }

    // DEBUG: union
    // DEBUG:     {
    // DEBUG:         float arr[2];
    // DEBUG:         struct
    // DEBUG:         {
    // DEBUG:             float a, b;
    // DEBUG:         };
    // DEBUG:     }
    public unsafe partial struct _0
    {
        [StructLayout(LayoutKind.Explicit, Size = 8)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal fixed float arr[2];

            [FieldOffset(0)]
            internal global::TestLib.StructBase._0._0.__Internal _0;
        }

        // DEBUG: struct
        // DEBUG:         {
        // DEBUG:             float a, b;
        // DEBUG:         }
        public unsafe partial class _0 // CS0542: member names cannot be the same as their enclosing type
        {
            [StructLayout(LayoutKind.Explicit, Size = 8)]
            public partial struct __Internal
            {
                [FieldOffset(0)]
                internal float a;

                [FieldOffset(4)]
                internal float b;
            }
        }
    }

```

### PR DESCRIPTION
**Pull request by josetr**
Fixes #1414

### CODE REVIEW

File: src/Generator/Passes/CleanInvalidDeclNamesPass.cs [hunk 1]
```diff
@@ -146,7 +146,14 @@ private static void Check(IEnumerable<Declaration> decls)
         {
             var anonymousDecls = decls.Where(p => string.IsNullOrEmpty(p.Name)).ToList();
             for (int i = 0; i < anonymousDecls.Count; i++)
-                anonymousDecls[i].Name = $"_{i}";
+            {
+                var anonymousDecl = anonymousDecls[i];
+
+                if (anonymousDecl.Namespace != null && anonymousDecl.Namespace.Name == anonymousDecl.Name)
```
Comment (ddobrev) [inline src/Generator/Passes/CleanInvalidDeclNamesPass.cs:152]: You could simplify to:
`anonymousDecl.Namespace?.Name == anonymousDecl.Name`

**Comment by ddobrev** [comment]
@josetr I'd like to start by saying I'm extremely happy to finally talk to you. I had been too busy for the last week and a half but now I'm happy with the opportunity to personally thank you for the extensive testing of our product.
Your fix is quite simple and therefore good by itself. I've added a minor suggestion. However, it lacks a just as simple unit test. So let me ask you to simply move the test case from your bug report in one of our test projects and this one will be ready to go.

File: src/Generator/Passes/CleanInvalidDeclNamesPass.cs (hunk 1 above)
Comment (josetr) [reply src/Generator/Passes/CleanInvalidDeclNamesPass.cs:152]: I avoided that because I thought that if `anonymousDecl.Name` is null and `anonymousDecl.NameSpace` is null then it would be detected as a collision even tho there isn't one.

**Comment by josetr** [comment]
No problem. I was just a bit surprised to find many bugs but I've realized that is mainly because I'm using the opposite `ParseOptions` that you guys use to test CppSharp.
