### PR TITLE
Fixed the generated #includes when renaming output files.

### LINKED ISSUE #868: Bad includes from CLI Generator when renaming outputs with GenerateName
OS: Windows
Target: MSVC

##### Brief Description
I was using a the GenerateName property of Driver.Options to provide a function that modified the names of my output files (adding "Wpr" to the end of the name in this case) to make it easier to identify the automatically generated wrappers. This worked until I tried to generate a wrapper for a class that made use of another wrapped class. The cpp file for the dependent wrapper tried to #include the other wrapper on it's original rather than modified name.

Please let me know if you need more information to reproduce this.

### PR DESCRIPTION
**Pull request by ktopouzi**
Fixes #868

### CODE REVIEW

File: src/Generator/Generators/CLI/CLITypeReferences.cs [hunk 1]
```diff
@@ -142,7 +142,7 @@ private void GenerateInclude(ASTRecord<Declaration> record)
         private string GetIncludePath(TranslationUnit translationUnit)
         {
             if (!DriverOptions.UseHeaderDirectories)
-                return translationUnit.FileName;
+                return $"{DriverOptions.GenerateName(translationUnit)}.h";
```
Comment (ddobrev) [inline src/Generator/Generators/CLI/CLITypeReferences.cs]: This must also work if GenerateName is not set i.e. is null.

File: tests/CLI/CLI.cs [hunk 2]
```diff
@@ -13,6 +13,11 @@ public CLITestsGenerator(GeneratorKind kind)
 
         public override void Setup(Driver driver)
         {
+            driver.Options.GenerateName = file =>
```
Comment (ddobrev) [inline tests/CLI/CLI.cs]: I guess this is set because you changed it in such a way that it crashes if GenerateName is not set. But as indicated above, this is not correct. Remove this piece, it must work without it.

File: tests/Common/Common.cs [hunk 3]
```diff
@@ -54,6 +54,11 @@ public override void Setup(Driver driver)
         {
             base.Setup(driver);
 
+            driver.Options.GenerateName = file =>
```
Comment (ddobrev) [inline tests/Common/Common.cs]: Remove.

File: tests/NamespacesDerived/NamespacesDerived.cs [hunk 4]
```diff
@@ -14,6 +14,11 @@ public NamespacesDerivedTests(GeneratorKind kind)
 
         public override void Setup(Driver driver)
         {
+            driver.Options.GenerateName = file =>
```
Comment (ddobrev) [inline tests/NamespacesDerived/NamespacesDerived.cs]: Remove.

File: tests/StandardLib/StandardLib.cs [hunk 5]
```diff
@@ -13,6 +13,11 @@ public StandardLibTestsGenerator(GeneratorKind kind)
 
         public override void Preprocess(Driver driver, ASTContext ctx)
         {
+            driver.Options.GenerateName = file =>
```
Comment (ddobrev) [inline tests/StandardLib/StandardLib.cs]: Remove.

File: tests/VTables/VTables.cs [hunk 6]
```diff
@@ -19,7 +19,10 @@ public override void SetupPasses(Driver driver)
 
         public override void Preprocess(Driver driver, ASTContext ctx)
         {
-
+            driver.Options.GenerateName = file =>
```
Comment (ddobrev) [inline tests/VTables/VTables.cs]: Remove.

File: build/Tests.lua [hunk 7]
```diff
@@ -18,11 +18,11 @@ function SetupExampleProject()
   SetupParser()
 end
 
-function SetupTestProject(name, extraFiles)
+function SetupTestProject(name, extraFiles, extension)
```
Comment (ddobrev) [inline build/Tests.lua]: Rename "extension" to "suffix" because of the precise meaning "extension" has for files. Rename it everywhere.

File: build/Tests.lua [hunk 8]
```diff
@@ -127,7 +127,14 @@ function LinkNUnit()
   }
 end
 
-function SetupTestProjectsCSharp(name, depends)
+function SetupTestProjectsCSharp(name, depends, extraFiles, extension)
+    if extension ~= nil then
+      nm = name .. extension 
+      str = "Std" .. extension
+    else
+      str = "Std"
```
Comment (ddobrev) [inline build/Tests.lua]: Set the name first for consistency with the first branch of the conditional.

File: src/Generator/Generators/CLI/CLITypeReferences.cs (hunk 1 above)
Comment (ddobrev) [inline src/Generator/Generators/CLI/CLITypeReferences.cs]: There are cases when headers have an extension other than ".h", even no extension at all. Handle this case in your logic.

File: src/Generator/Generators/CLI/CLITypeReferences.cs [hunk 9]
```diff
@@ -142,7 +142,13 @@ private void GenerateInclude(ASTRecord<Declaration> record)
         private string GetIncludePath(TranslationUnit translationUnit)
         {
             if (!DriverOptions.UseHeaderDirectories)
-                return translationUnit.FileName;
+                if(DriverOptions.GenerateName != null)
```
Comment (ddobrev) [inline src/Generator/Generators/CLI/CLITypeReferences.cs]: Fix your indentation - if the indentation is correct, merge the if-s with &&. Add a space after the if.
